// Top-level build.gradle
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        // For latest versions, see https://developer.android.com/reference/tools/gradle-api
        classpath 'com.android.tools.build:gradle:8.11.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
